include ../config

all: hello viewer

hello: main-hello.o
	$(CC) -o ../nw-$@ $^ $(LIBS)

viewer: main-viewer.o networld.o
	$(CC) -o ../nw-$@ $^ $(LIBS)

%.o: %.c
	$(CC) -c $< $(CFLAGS)

config:
	rm config
	"OS= `uname`" >> config

clean:
	rm -rf *.o


